// <auto-generated />
using System;
using InternalKnowledgeCopilot.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternalKnowledgeCopilot.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513091339_AddEvaluation")]
    partial class AddEvaluation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_status");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("AiInteractionId", "UserId")
                        .IsUnique();

                    b.HasIndex("Value", "ReviewStatus");

                    b.ToTable("ai_feedback", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("answer");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("low")
                        .HasColumnName("confidence");

                    b.Property<string>("ConflictsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("conflicts_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("MissingInformationJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("missing_information_json");

                    b.Property<bool>("NeedsClarification")
                        .HasColumnType("INTEGER")
                        .HasColumnName("needs_clarification");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<Guid?>("ScopeDocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_document_id");

                    b.Property<Guid?>("ScopeFolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_folder_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<string>("SuggestedFollowUpsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_follow_ups_json");

                    b.Property<int>("UsedDocumentCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("used_document_count");

                    b.Property<int>("UsedWikiCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("used_wiki_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ai_interactions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("DocumentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_version_id");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("excerpt");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("section_title");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<Guid?>("WikiPageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id");

                    b.HasIndex("AiInteractionId");

                    b.ToTable("ai_interaction_sources", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiQualityIssueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiFeedbackId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_feedback_id");

                    b.Property<Guid>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset?>("ClassifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("classified_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_json");

                    b.Property<string>("FailureType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_type");

                    b.Property<string>("RecommendedActionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_actions_json");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("RootCauseHypothesis")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("root_cause_hypothesis");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AiFeedbackId")
                        .IsUnique();

                    b.HasIndex("AiInteractionId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ai_quality_issues", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_version_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FolderId", "Title");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_summary");

                    b.Property<string>("ExtractedTextPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("extracted_text_path");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_extension");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("NormalizedTextPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_text_path");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessingWarningsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("processing_warnings_json");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int?>("SectionCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("section_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_file_path");

                    b.Property<string>("TextHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("text_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("document_versions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_answer");

                    b.Property<string>("ExpectedKeywordsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_keywords_json");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<Guid?>("SourceFeedbackId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_feedback_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FolderId");

                    b.HasIndex("SourceFeedbackId");

                    b.HasIndex("IsActive", "CreatedAt");

                    b.ToTable("evaluation_cases", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("FailedCases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_cases");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PassedCases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passed_cases");

                    b.Property<int>("TotalCases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_cases");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("evaluation_runs", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationRunResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actual_answer");

                    b.Property<Guid?>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EvaluationCaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_case_id");

                    b.Property<Guid>("EvaluationRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_run_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passed");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("AiInteractionId");

                    b.HasIndex("EvaluationRunId");

                    b.HasIndex("EvaluationCaseId", "CreatedAt");

                    b.ToTable("evaluation_run_results", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanView")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_view");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("FolderId", "TeamId")
                        .IsUnique();

                    b.ToTable("folder_permissions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.KnowledgeCorrectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiFeedbackId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_feedback_id");

                    b.Property<Guid>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("CorrectionText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correction_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<Guid>("QualityIssueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("quality_issue_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility_scope");

                    b.HasKey("Id");

                    b.HasIndex("AiFeedbackId");

                    b.HasIndex("AiInteractionId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FolderId");

                    b.HasIndex("QualityIssueId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("knowledge_corrections", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.ProcessingJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("processing_jobs", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.RetrievalHintEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("correction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("HintText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("hint_text");

                    b.HasKey("Id");

                    b.HasIndex("CorrectionId");

                    b.ToTable("retrieval_hints", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<Guid?>("PrimaryTeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_team_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimaryTeamId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserFolderPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanView")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_view");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "FolderId")
                        .IsUnique();

                    b.ToTable("user_folder_permissions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.WikiDraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_by_user_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("MissingInformationJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("missing_information_json");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_reason");

                    b.Property<string>("RelatedDocumentsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("related_documents_json");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_document_id");

                    b.Property<Guid>("SourceDocumentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_document_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("SourceDocumentVersionId");

                    b.HasIndex("Status");

                    b.ToTable("wiki_drafts", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.WikiPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsCompanyPublicConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_company_public_confirmed");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_by_user_id");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_document_id");

                    b.Property<Guid>("SourceDocumentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_document_version_id");

                    b.Property<Guid>("SourceDraftId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_draft_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility_scope");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("SourceDocumentVersionId");

                    b.HasIndex("SourceDraftId")
                        .IsUnique();

                    b.HasIndex("VisibilityScope");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany()
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiInteraction");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionSourceEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany("Sources")
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiInteraction");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiQualityIssueEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", "AiFeedback")
                        .WithMany()
                        .HasForeignKey("AiFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany()
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiFeedback");

                    b.Navigation("AiInteraction");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentVersionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationCaseEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", "SourceFeedback")
                        .WithMany()
                        .HasForeignKey("SourceFeedbackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");

                    b.Navigation("Folder");

                    b.Navigation("SourceFeedback");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationRunEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationRunResultEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany()
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationCaseEntity", "EvaluationCase")
                        .WithMany()
                        .HasForeignKey("EvaluationCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationRunEntity", "EvaluationRun")
                        .WithMany("Results")
                        .HasForeignKey("EvaluationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiInteraction");

                    b.Navigation("EvaluationCase");

                    b.Navigation("EvaluationRun");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderPermissionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany("TeamPermissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.KnowledgeCorrectionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", "AiFeedback")
                        .WithMany()
                        .HasForeignKey("AiFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany()
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiQualityIssueEntity", "QualityIssue")
                        .WithMany()
                        .HasForeignKey("QualityIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiFeedback");

                    b.Navigation("AiInteraction");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");

                    b.Navigation("Folder");

                    b.Navigation("QualityIssue");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.RetrievalHintEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.KnowledgeCorrectionEntity", "Correction")
                        .WithMany()
                        .HasForeignKey("CorrectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correction");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", "PrimaryTeam")
                        .WithMany("Users")
                        .HasForeignKey("PrimaryTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryTeam");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserFolderPermissionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany("UserPermissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.WikiDraftEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentVersionEntity", "SourceDocumentVersion")
                        .WithMany()
                        .HasForeignKey("SourceDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SourceDocument");

                    b.Navigation("SourceDocumentVersion");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.WikiPageEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentVersionEntity", "SourceDocumentVersion")
                        .WithMany()
                        .HasForeignKey("SourceDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.WikiDraftEntity", "SourceDraft")
                        .WithMany()
                        .HasForeignKey("SourceDraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("PublishedByUser");

                    b.Navigation("SourceDocument");

                    b.Navigation("SourceDocumentVersion");

                    b.Navigation("SourceDraft");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.EvaluationRunEntity", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TeamPermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
