// <auto-generated />
using System;
using InternalKnowledgeCopilot.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternalKnowledgeCopilot.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509034851_AddAiFeedback")]
    partial class AddAiFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_status");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("AiInteractionId", "UserId")
                        .IsUnique();

                    b.HasIndex("Value", "ReviewStatus");

                    b.ToTable("ai_feedback", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<bool>("NeedsClarification")
                        .HasColumnType("INTEGER")
                        .HasColumnName("needs_clarification");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<Guid?>("ScopeDocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_document_id");

                    b.Property<Guid?>("ScopeFolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_folder_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<int>("UsedDocumentCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("used_document_count");

                    b.Property<int>("UsedWikiCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("used_wiki_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ai_interactions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiInteractionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_interaction_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("DocumentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_version_id");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("excerpt");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<Guid?>("WikiPageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id");

                    b.HasIndex("AiInteractionId");

                    b.ToTable("ai_interaction_sources", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_version_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FolderId", "Title");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ExtractedTextPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("extracted_text_path");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_extension");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_file_path");

                    b.Property<string>("TextHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("text_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("document_versions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanView")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_view");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("FolderId", "TeamId")
                        .IsUnique();

                    b.ToTable("folder_permissions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.ProcessingJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("processing_jobs", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<Guid?>("PrimaryTeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_team_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimaryTeamId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserFolderPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanView")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_view");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "FolderId")
                        .IsUnique();

                    b.ToTable("user_folder_permissions", (string)null);
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiFeedbackEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany()
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiInteraction");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionSourceEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", "AiInteraction")
                        .WithMany("Sources")
                        .HasForeignKey("AiInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiInteraction");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentVersionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderPermissionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany("TeamPermissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", "PrimaryTeam")
                        .WithMany("Users")
                        .HasForeignKey("PrimaryTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryTeam");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserFolderPermissionEntity", b =>
                {
                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", "Folder")
                        .WithMany("UserPermissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.AiInteractionEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.FolderEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TeamPermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("InternalKnowledgeCopilot.Api.Infrastructure.Database.Entities.TeamEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
